# Makefile

all:
	-cd platformer; $(MAKE) $@
	-cd pong; $(MAKE) $@
	-cd shooter; $(MAKE) $@
	-cd skel; $(MAKE) $@

clean:
	-cd platformer; $(MAKE) $@
	-cd pong; $(MAKE) $@
	-cd shooter; $(MAKE) $@
	-cd skel; $(MAKE) $@
