# Makefile

all:
	cd pong; $(MAKE) $@
	cd shooter; $(MAKE) $@
	cd platformer; $(MAKE) $@
	cd isometric; $(MAKE) $@

clean:
	-cd pong; $(MAKE) $@
	-cd shooter; $(MAKE) $@
	-cd platformer; $(MAKE) $@
	-cd isometric; $(MAKE) $@
